apps:
  api:
    port: 3000
    privatePort: 4000
    useCachingInterceptor: true
  cacheWarmer:
    port: 4001
  queueWorker:
    port: 4002
  transactionsProcessor:
    port: 4003
    maxLookBehind: 100
libs:
  common:
    network: ${NETWORK}
    urls:
      api: ${API_URL}
    database:
      host: ${DATABASE_HOST}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      name: ${DATABASE_NAME}
      tlsAllowInvalidCertificates: true
    redis:
      host: ${REDIS_HOST}
      port: ${num:REDIS_PORT}
    nativeAuth:
      # maxExpirySeconds:
      acceptedOrigins:
        - utils.multiversx.com
    security:
      admins: []
    # rateLimiterSecret:
