urls:
  api: 'https://devnet-api.elrond.com'
  swagger:
    - 'https://devnet-microservice.elrond.com'
    - 'https://testnet-microservice.elrond.com'
    - 'https://microservice.elrond.com'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  name: 'api'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  cacheWarmer:
    enabled: true
    port: 5201
  transactionProcessor:
    enabled: true
    port: 5202
    maxLookBehind: 100
  queueWorker:
    enabled: true
    port: 8000
security:
  jwtSecret: ''
  admins:
